#!/bin/bash

DATE=`date +"%Y_%m_%d_%H_%M_%S"`
objectName="java_provision_${DYNO}_${DATE}.hprof"
file=/tmp/java.hprof
bucket=java-heapdumps
resource="/${bucket}/${objectName}"
contentType="application/octet-stream"
dateValue=`date -R`
stringToSign="PUT\n\n${contentType}\n${dateValue}\n${resource}"
s3Key=${AWS_ACCESS_KEY_ID}
s3Secret=${AWS_SECRET_ACCESS_KEY}
signature=`echo -en ${stringToSign} | openssl sha1 -hmac ${s3Secret} -binary | base64`
curl -v -i -X PUT -T "${file}" \
	-H "Host: ${bucket}.s3.amazonaws.com" \
	-H "Date: ${dateValue}" \
	-H "Content-Type: ${contentType}" \
	-H "Authorization: AWS ${s3Key}:${signature}" \
	https://${bucket}.s3.amazonaws.com/${objectName}